[package]
name = "zeke-contract"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = { git = "https://github.com/solana-labs/solana.git", version = "1.11.5" }
solana-client = { git = "https://github.com/solana-labs/solana.git", version = "1.11.5" }
yaml-rust = "0.4"
thiserror = "1"
home = "0.5.3"
borsh = "0.9.1"
