[package]
name = "zeke-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.1"
clap = { version = "3.1.5", features = ["cargo", "env"] }
home = "0.5.3"
solana-client = { git = "https://github.com/dmakarov/solana.git", version = "1.11.5" }
solana-sdk = { git = "https://github.com/dmakarov/solana.git", version = "1.11.5" }
thiserror = "1"
yaml-rust = "0.4"
