[package]
name = "greetings"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.1", features = ["derive", "unstable__schema"] }
solana-program = { git = "https://github.com/anza-xyz/agave.git", version = "2.1.0" }

[lib]
name = "greetings"
crate-type = ["cdylib", "lib"]
